import SessionProvider from '@/components/SessionProvider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="flex flex-1 flex-col">
            {children}
            <ToastContainer
              position="top-center"
              autoClose={3000}
              closeOnClick
              pauseOnFocusLoss={false}
              theme="dark"
            />
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
